name: NASA Project CI
on:
  push:
    branches: [master]
  pull_requst:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-lates
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm run build --prefix client
